//DeparatedTemplatesLib (Arrays.lib)
#include"stdafx.h"
#include"Constants.h"
#include"FillRand.h"
#include"Print.h"
#include"Sort.h"
#include"Sum.h"
#include"Avg.h"
#include"MinValueIn.h"
#include"MaxValueIn.h"
#include"ShiftLeft.h"
#include"ShiftRight.h"